[package]
name = "blender_file_version_switcher"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.0"
dirs = "5.0.1"
flate2 = "1.0"
getopts = "0.2"
json5 = "0.4.1"
serde = { version = "1.0.202", features = ["derive"] }
zstd = "0.13"
